codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "0...100"

  status:
    project: true
    patch: true
    changes: no

ignore:
  - "**/*.spec.ts"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, reach, diff"
  behavior: default
  require_changes: no
