version: 2.1

executors:
  ng-executor:
    docker:
      - image: angular/ngcontainer
    working_directory: ~/ngx-state

jobs:
  build:
    executor: ng-executor
    steps:
      # CHECKOUT CODE
      - checkout

      # INSTALL GLOBAL DEPENDENCIES
      - run:
          name: Install Global Dependencies
          command: yarn global add codecov tslint@~5.15.0 typescript@~3.5.3

      # INSTALL APP DEPENDENCIES
      - run:
          name: Install App Dependencies
          command: yarn install

      # RUN LINTING
      - run:
          name: TSlint
          command: yarn lint

      # RUN BUILD
      - run:
          name: Build Library
          command: yarn build

      - persist_to_workspace:
          root: ~/
          paths:
            - ngx-state

  test:
    executor: ng-executor
    steps:
      - attach_workspace:
          at: ~/

      # RUN TESTS
      - run:
          name: Angular Unit Tests  && Codecov Coverage
          command: xvfb-run -a yarn test:ci

      # REPORT TEST COVERAGE
      - run:
          name: Report to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
