version: 2.1

executors:
  ng-executor:
    docker:
      - image: angular/ngcontainer
    working_directory: ~/ngx-state

jobs:
  build:
    executor: ng-executor
    steps:
      # CHECKOUT CODE
      - checkout

      - restore_cache:
          key: deps-cache-{{ checksum "yarn.lock" }}

      # INSTALL GLOBAL DEPENDENCIES
      - run:
          name: Install Global Dependencies
          command: yarn global add codecov tslint@~5.15.0 typescript@~3.5.3 semantic-release @angular/cli

      # INSTALL APP DEPENDENCIES
      - run:
          name: Install App Dependencies
          command: yarn install

      - save_cache:
          key: deps-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules

      # RUN LINTING
      - run:
          name: TSlint
          command: yarn lint

      # RUN BUILD
      - run:
          name: Build Library
          command: yarn build

      - save_cache:
          key: dist-{{ .Revision }}
          paths:
              - dist

  test:
    executor: ng-executor
    steps:
      - checkout

      - restore_cache:
          key: deps-cache-{{ checksum "yarn.lock" }}

      - restore_cache:
          key: dist-{{ .Revision }}

      # RUN TESTS
      - run:
          name: Angular Unit Tests  && Codecov Coverage
          command: xvfb-run -a yarn test:ci

      # REPORT TEST COVERAGE
      - run:
          name: Report to Codecov
          command: bash <(curl -s https://codecov.io/bash)

  release:
    executor: ng-executor
    steps:
      - checkout

      - restore_cache:
          key: deps-cache-{{ checksum "yarn.lock" }}

      - restore_cache:
          key: dist-{{ .Revision }}

      - run:
         name: release
         command: yarn semantic-release || true

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - test
          filters:
            branches:
              only: master
